# Generated by Django 5.2.16 on 2026-08-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="название")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="slug")),
            ],
            options={
                "verbose_name": "удобство",
                "verbose_name_plural": "удобства",
                "ordering": ("name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="название")),
                ("slug", models.SlugField(max_length=160, unique=True, verbose_name="slug")),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="цена за ночь"),
                ),
                ("max_adults", models.PositiveSmallIntegerField(verbose_name="максимум взрослых")),
                (
                    "max_children",
                    models.PositiveSmallIntegerField(default=0, verbose_name="максимум детей"),
                ),
                (
                    "area_sqm",
                    models.DecimalField(decimal_places=2, max_digits=6, verbose_name="площадь, м²"),
                ),
                ("bed_count", models.PositiveSmallIntegerField(verbose_name="количество кроватей")),
                (
                    "confirmation_mode",
                    models.CharField(
                        choices=[("automatic", "автоматическое"), ("manual", "ручное")],
                        default="automatic",
                        max_length=16,
                        verbose_name="режим подтверждения",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_types",
                        to="inventory.amenity",
                        verbose_name="удобства",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория номера",
                "verbose_name_plural": "категории номеров",
                "ordering": ("name", "pk"),
                "permissions": (
                    (
                        "manage_roomtype_commercial_fields",
                        "Может управлять коммерческими полями категории номера",
                    ),
                ),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price_per_night__gt", 0)),
                        name="inventory_room_type_price_gt_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("area_sqm__gt", 0)),
                        name="inventory_room_type_area_gt_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_adults__gte", 1)),
                        name="inventory_room_type_adults_gte_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_children__gte", 0)),
                        name="inventory_room_type_children_gte_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("bed_count__gte", 1)),
                        name="inventory_room_type_beds_gte_one",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoomTypeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(verbose_name="URL изображения")),
                ("alt_text", models.CharField(max_length=255, verbose_name="альтернативный текст")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="порядок")),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory.roomtype",
                        verbose_name="категория номера",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение категории номера",
                "verbose_name_plural": "изображения категорий номеров",
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=32, unique=True, verbose_name="номер")),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="inventory.roomtype",
                        verbose_name="категория номера",
                    ),
                ),
            ],
            options={
                "verbose_name": "комната",
                "verbose_name_plural": "комнаты",
                "ordering": ("number", "pk"),
            },
        ),
    ]
