# Generated by Django 5.2.16 on 2026-08-08 07:55

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name='MaintenanceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_blocks', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_blocks', to='inventory.room', verbose_name='комната')),
            ],
            options={
                'verbose_name': 'служебный блок',
                'verbose_name_plural': 'служебные блоки',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='RoomOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay', django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='проживание')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='bookings.booking', verbose_name='бронь')),
                ('maintenance_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='inventory.maintenanceblock', verbose_name='служебный блок')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='inventory.room', verbose_name='комната')),
            ],
            options={
                'verbose_name': 'занятость комнаты',
                'verbose_name_plural': 'занятость комнат',
                'required_db_vendor': 'postgresql',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('maintenance_block__isnull', True)), models.Q(('booking__isnull', True), ('maintenance_block__isnull', False)), _connector='OR'), name='inventory_room_occupancy_exactly_one_holder'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=(('room', '='), ('stay', '&&')), name='inventory_room_occupancy_no_overlapping_stays')],
            },
        ),
    ]
