# Generated by Django 5.2.16 on 2026-08-08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("check_in", models.DateField(verbose_name="заезд")),
                ("check_out", models.DateField(verbose_name="выезд")),
                ("adults", models.PositiveSmallIntegerField(verbose_name="взрослые")),
                ("children", models.PositiveSmallIntegerField(verbose_name="дети")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_confirmation", "ожидает подтверждения"),
                            ("awaiting_payment", "ожидает оплаты"),
                            ("paid", "оплачена"),
                            ("rejected", "отклонена"),
                            ("cancelled", "отменена"),
                            ("expired", "истекла"),
                        ],
                        max_length=24,
                        verbose_name="статус",
                    ),
                ),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True, verbose_name="срок удержания")),
                ("payment_due_at", models.DateTimeField(blank=True, null=True, verbose_name="срок оплаты")),
                (
                    "cancellable_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="отмена доступна до"),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="истекает")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создана")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="обновлена")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="клиент",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="inventory.roomtype",
                        verbose_name="категория номера",
                    ),
                ),
            ],
            options={
                "verbose_name": "бронь",
                "verbose_name_plural": "брони",
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(("check_in__lt", models.F("check_out"))),
                        name="bookings_booking_check_in_before_check_out",
                    ),
                    models.CheckConstraint(
                        condition=Q(("adults__gte", 1)),
                        name="bookings_booking_adults_gte_one",
                    ),
                    models.CheckConstraint(
                        condition=Q(("children__gte", 0)),
                        name="bookings_booking_children_gte_zero",
                    ),
                    models.CheckConstraint(
                        condition=Q(
                            ("status__in", [
                                "pending_confirmation",
                                "awaiting_payment",
                                "paid",
                                "rejected",
                                "cancelled",
                                "expired",
                            ])
                        ),
                        name="bookings_booking_status_allowed",
                    ),
                    models.CheckConstraint(
                        condition=(
                            Q(
                                ("expires_at__isnull", False),
                                ("status__in", ["pending_confirmation", "awaiting_payment"]),
                            )
                            | Q(
                                ("expires_at__isnull", True),
                                ("status__in", ["paid", "rejected", "cancelled", "expired"]),
                            )
                        ),
                        name="bookings_booking_expires_at_matches_status",
                    ),
                ],
            },
        ),
    ]
