# Generated by Django 5.2.16 on 2026-08-02 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='название гостиницы')),
                ('tagline', models.CharField(max_length=240, verbose_name='короткое описание')),
                ('about_title', models.CharField(max_length=200, verbose_name='заголовок блока «О гостинице»')),
                ('about_text', models.TextField(verbose_name='текст блока «О гостинице»')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('phone', models.CharField(max_length=32, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('check_in_time', models.TimeField(default='14:00', verbose_name='время заезда')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='время выезда')),
                ('footer_text', models.CharField(max_length=255, verbose_name='текст в footer')),
                ('seo_title', models.CharField(max_length=160, verbose_name='SEO title')),
                ('seo_description', models.CharField(max_length=320, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO keywords')),
            ],
            options={
                'verbose_name': 'профиль гостиницы',
                'verbose_name_plural': 'профиль гостиницы',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='content_hotel_profile_is_singleton')],
            },
        ),
        migrations.CreateModel(
            name='HotelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Короткий символ или эмодзи для карточки преимущества.', max_length=16, verbose_name='иконка')),
                ('title', models.CharField(max_length=120, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='content.hotelprofile', verbose_name='профиль гостиницы')),
            ],
            options={
                'verbose_name': 'преимущество гостиницы',
                'verbose_name_plural': 'преимущества гостиницы',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(max_length=80, verbose_name='надзаголовок')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('body', models.TextField(blank=True, verbose_name='текст')),
                ('image_url', models.URLField(blank=True, verbose_name='URL изображения')),
                ('primary_cta_label', models.CharField(blank=True, max_length=80, verbose_name='текст основной кнопки')),
                ('primary_cta_url', models.CharField(blank=True, max_length=255, verbose_name='ссылка основной кнопки')),
                ('secondary_cta_label', models.CharField(blank=True, max_length=80, verbose_name='текст дополнительной кнопки')),
                ('secondary_cta_url', models.CharField(blank=True, max_length=255, verbose_name='ссылка дополнительной кнопки')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='content.hotelprofile', verbose_name='профиль гостиницы')),
            ],
            options={
                'verbose_name': 'hero-слайд',
                'verbose_name_plural': 'hero-слайды',
                'ordering': ('sort_order', 'pk'),
            },
        ),
    ]
